name: PR-Snyk-Check-pulling-test-results-from-CircleCI

on: 
  pull_request:
    types: [opened,reopened,synchronized]
  
jobs:
  snyk_check:
    runs-on: ubuntu-latest
    name: Snyk PR Check
    steps:
    - name: Snyk prevent
      id: snyk-prevent
      uses: snyk-tech-services/github-actions-snyk-prevent-job-from-circleci@master
      # env:
      #   SNYK_TOKEN: ${{ secrets.snykToken }}
      with:
        ghToken: ${{ secrets.ghToken }}
        snykToken: ${{ secrets.snykToken }}
        circleCIToken: ${{ secrets.circleCIToken }}
        workflowName: wf-build-test
        snykTestOutputFilename: snykTestResults
        # snykArguments: "--severity-threshold=high"
        # breakBuild: false
        # fullScan: false

